// components/button/button.jsx
import Icon from '../icon'
import { getChild } from '../_tool/utils'
export default {
  name: "Button",
  props: {
    buttonType: {
      default: "button",
      validator(value) {
        return ["button", "submit", "reset"].indexOf(value) >= 0;
      }
    },
    icon: String,
    block: Boolean,
    size: {
      default: 'default',
      validator(value) {
        return ["small", "large", "default"].indexOf(value) >= 0;
      }
    },
    loading: Boolean,
    circle: Boolean,
    hollow: Boolean,
    type: {
      validator(value) {
        return (
          ["danger", "primary", "link", "default", "dashed"].indexOf(value) >= 0
        );
      },
      default: 'default'
    },
    disabled: Boolean
  },
  computed: {
    classes() {
      const { type, loading, circle, hollow, $slots, icon, size } = this
      const onlyIcon = !getChild($slots.default).length && icon
      return [
        "k-btn",
        {
          [`k-btn-${type}`]: !!type,
          ["k-btn-sm"]: size == 'small',
          ["k-btn-block"]: !!this.block,
          ["k-btn-loading"]: loading,
          ["k-btn-icon-only"]: onlyIcon,
          ["k-btn-lg"]: size == 'large',
          ["k-btn-circle"]: !!circle,
          ["k-btn-hollow"]: !!hollow
        }
      ];
    }
  },
  methods: {
    click(e) {
      if (!this.loading) {
        this.$emit('click', e)
      }
    }
  },

  render() {
    const { classes, $slots, $attrs, disabled, click, buttonType, icon, loading, $listeners } = this
    const props = {
      attrs: { ...$attrs, disabled, type: buttonType },
      class: classes,
      on: {
        ...$listeners,
        click: click
      }
    }
    const iconType = loading ? 'sync' : icon;
    const iconNode = iconType ? <Icon type={iconType} spin={loading} /> : null
    const child = getChild($slots.default)
    const kid = child.map(c => {
      if (typeof c.text == 'string') {
        let text = c.text.trim()
        return <span>{text}</span>
      }
      return c
    })
    const button = (
      <button {...props} >
        {iconNode}
        {kid}
      </button >
    )
    return button
  }
};

// src/components/button/button.vue
<template>
  <button :type="buttonType" :class="classes" :disabled="disabled" @click="click">
    <Icon :type="icon" :class="iconClasses" v-if="icon&&iconAlign=='left'&&!loading" />
    <Icon type="ios-sync" spin v-if="loading" />
    <span v-if="showSlot">
      <slot></slot>
    </span>
    <Icon :type="icon" :class="iconClasses" v-if="icon&&iconAlign=='right'&&!loading" />
  </button>
</template>
<script>
import Icon from '../icon'
export default {
  name: "Button",
  components: { Icon },
  props: {
    buttonType: {
      default: "button",
      validator(value) {
        return ["button", "submit", "reset"].indexOf(value) >= 0;
      }
    },
    icon: String,
    iconAlign: { type: String, default: 'left' },
    mini: { type: Boolean, default: false },
    large: { type: Boolean, default: false },
    loading: Boolean,
    circle: { type: Boolean, default: false },
    hollow: { type: Boolean, default: false },
    type: {
      validator(value) {
        return (
          ["danger", "primary", "warning", "success", "gray", "link", "default"].indexOf(value) >= 0
        );
      }
    },
    disabled: Boolean
  },
  data() {
    return {
      showSlot: true
    }
  },
  computed: {
    iconClasses() {
      return [{ 'icon-left': this.iconAlign == 'left', 'icon-right': this.iconAlign == 'right' }];
    },
    classes() {
      return [
        "k-btn",
        {
          [`k-btn-${this.type}`]: !!this.type,
          ["k-btn-mini"]: !!this.mini,
          ["k-btn-loading"]: this.loading,
          ["k-btn-icon-only"]: !this.showSlot,
          ["k-btn-lg"]: !!this.large && !this.mini,
          ["k-btn-circle"]: !!this.circle,
          ["k-btn-hollow"]: !!this.hollow
        }
      ];
    }
  },
  mounted() {
    this.showSlot = this.$slots.default !== undefined;
  },
  methods: {
    click(e) {
      if (!this.loading) {
        this.$emit('click', e)
      }
    }
  }
};
</script>
