// src/components/button/button.vue
<template>
  <button :type="buttonType" :class="classes" :disabled="disabled" @click="click">
    <Icon :type="icon" :class="iconClasses" v-if="icon&&iconAlign=='left'&&!loading" />
    <Icon type="ios-sync" spin v-if="loading" />
    <span v-if="showSlot">
      <slot></slot>
    </span>
    <Icon :type="icon" :class="iconClasses" v-if="icon&&iconAlign=='right'&&!loading" />
  </button>
</template>
<script>
import Icon from '../icon'
export default {
  name: "Button",
  components: { Icon },
  props: {
    buttonType: {
      default: "button",
      validator(value) {
        return ["button", "submit", "reset"].indexOf(value) >= 0;
      }
    },
    icon: String,
    iconAlign: { type: String, default: 'left' },
    mini: { type: Boolean, default: false },
    large: { type: Boolean, default: false },
    loading: Boolean,
    circle: { type: Boolean, default: false },
    hollow: { type: Boolean, default: false },
    type: {
      validator(value) {
        return (
          ["danger", "primary", "warning", "success", "gray", "link", "default"].indexOf(value) >= 0
        );
      }
    },
    disabled: Boolean
  },
  data() {
    return {
      showSlot: true
    }
  },
  computed: {
    iconClasses() {
      return [{ 'icon-left': this.iconAlign == 'left', 'icon-right': this.iconAlign == 'right' }];
    },
    classes() {
      return [
        "k-btn",
        {
          [`k-btn-${this.type}`]: !!this.type,
          ["k-btn-mini"]: !!this.mini,
          ["k-btn-loading"]: this.loading,
          ["k-btn-icon-only"]: !this.showSlot,
          ["k-btn-lg"]: !!this.large && !this.mini,
          ["k-btn-circle"]: !!this.circle,
          ["k-btn-hollow"]: !!this.hollow
        }
      ];
    }
  },
  mounted() {
    this.showSlot = this.$slots.default !== undefined;
  },
  methods: {
    click(e) {
      if (!this.loading) {
        this.$emit('click', e)
      }
    }
  }
};
</script>

// components/radio/button.jsx
import Button from '../button';
export default {
  name: "RadioButton",
  props: {
    value: { type: [String, Number, Boolean], default: false },
    disabled: Boolean,
    label: [String, Number],
  },
  inject: {
    FormItem: { default: null },
    groupContext: { default: null },
  },
  data() {
    return {
      checked: false
    }
  },
  methods: {
    change() {
      let { value, $slots, label, groupContext } = this
      this.checked = true
      if (groupContext) {
        label = label || $slots.default.text
        groupContext.change({ label, value })
      } else {
        this.$emit("input", checked);
        this.$emit("change", e);
        this.FormItem && this.FormItem.testValue(checked)
      }
    }
  },

  render() {
    let { disabled, change, $slots, label, groupContext, value, checked, $attrs } = this
    let prop = {}
    if (groupContext) {
      checked = groupContext.value == value
      let { mini, large, hollow } = groupContext
      disabled = disabled || groupContext.disabled
      prop = { disabled, mini, large, hollow, type: checked ? 'primary' : 'default' }
    }
    const props = {
      attrs: { ...$attrs },
      on: { click: change },
      props: { ...prop }
    }
    return (
      <Button {...props}>{label || $slots.default}</Button>
    )
  }
};
